### ISSUE TITLE
Updated German translation including the miss call and msg app detected

### ISSUE THREAD

**Issue by jokage** [ClockworkMod/DeskSMS#11]
https://github.com/jokage/DesktopSMSResources/blob/master/values/strings.xml

can someone tell me how to properly send stuff? or tell me where the guide to use commits is?
I'm really new and confused I did read the manual but enlightenment is needed .

**Comment by koush** [comment]
You should delete your existing repository and refork mine.

Then look in res/values-de for the German translation. The way you are doing it now is actually removing the English translation :) So I need to copy it, and then restore the english version
