### ISSUE TITLE
Mark SMS as read on phone

### ISSUE THREAD

**Issue by periclytes** [ClockworkMod/DeskSMS#13]
App works great, but the SMS are left with an unread state on the phone's messaging app.  Please add support to mark them as read.

HTC Thunderbolt running CM7 RC1.2

**Comment by koush** [comment]
I'll look into this, but it's pretty low on the priority list. I have some better/killer features coming up that will take a lot of time :)

**Comment by koush** [comment]
Fixed for web interface.
Also needs to be fixed on outgoing gtalk and gmail.

**Comment by koush** [comment]
All outgoing messages now also mark the inbox as read. (1074+)
