### ISSUE TITLE
Wifi trigger

### ISSUE THREAD

**Issue by kimir** [ClockworkMod/DeskSMS#21]
If you connect to a certain wifi connection, DesktopSMS automatically turns on gmail or gtalk.

**Comment by kimir** [comment]
Should this be under Poll Requests? Sorry about that...

**Comment by koush** [comment]
What version of the application?

**Comment by kimir** [comment]
1.0.3.0 also, is there a way to use the widget to turn it completely off?
On Jul 29, 2011 3:03 AM, "koush" <
reply@reply.github.com>
wrote:

**Comment by koush** [comment]
The weird toggling problems of settings should be fixed.
