### ISSUE TITLE
SMS Time Fix screws up sync

### ISSUE THREAD

**Issue by koush** [ClockworkMod/DeskSMS#26]
https://market.android.com/details?id=com.mattprecious.smsfix

It swoops in and changes the timestamp to 4 hours in the past for example. Outbox messages I believe remain at the "correct" time.
This screws up sync, as it will never see outbox messages.

**Comment by koush** [comment]
Fixed by doing incremental sync off of _id.

**Comment by i1024get** [comment]
Started have this issue in the last week. Help is appreciated. I love using this software at work. If I can catch the message in the notification it is fine, but often times I can't. Thanks for the help
