### ISSUE TITLE
Chrome extension and webpage at the same time issue

### ISSUE THREAD

**Issue by Kdroidx** [ClockworkMod/DeskSMS#31]
When on the website the extension stays with the notification, then clicking the extension button to get rid of the notification only makes it go away until the next text incomes, then the notification numbers just keep piling up.

**Comment by koush** [comment]
So, you don't want it to show a badge when you have the webpage open? I suppose that is a matter of preference. What if the page is opened but in a tab that is just in the background somewhere? How does the user know that a notification came in?
