### ISSUE TITLE
Rom manager , captivate Rom Fasty

### ISSUE THREAD

**Issue by Lostlogic89** [ClockworkMod/DeskSMS#36]
I uploaded that rom about a week ago ,however it's always giving download error.Comments are directed that it's a rom manager server issue which i doubt .Any help would be appreciated .

**Comment by koush** [comment]
Wrong place to post this. I'll take a look.

**Comment by koush** [comment]
I just tested all your download links in the browser, and they worked fine in the browser. Via the android app they fail.

I believe this is because you have spaces in the file name. Please do not do that :)

**Comment by Lostlogic89** [comment]
Ok srry  and thanks .
