### ISSUE TITLE
Messages arent sent/recived

### ISSUE THREAD

**Issue by NmE** [ClockworkMod/DeskSMS#52]
Having issues with the latest version of DeskSMS (1083):
Using GTalk and been using it for 3-4 weeks without any issues, but after updating to the latest version the messages arent received on the phone, or sent for that matter.

The messages are received on my Gtalk account and if I test the connection on the web - the message is received.

**Comment by koush** [comment]
There was a bug in 1082 where the desksms client would log out silently. Can you try relogging into the desksms application on android and let me know if that fixes it?

**Comment by NmE** [comment]
Fixed in 1082, thanks :)
