### ISSUE TITLE
Sending Messages From Chrome

### ISSUE THREAD

**Issue by red261** [ClockworkMod/DeskSMS#53]
When I try to send a message to a contact, the chrome extension and website fail to send. I continue to receive messages on the site and any messages that I send from my phone show up. When I test the connection it says the push connection to the phone has failed to connect. I have tried logging out and in on both the phone and website with no difference. After a random time, it begins to work again, but it starts acting up after another seemingly random period.

**Comment by koush** [comment]
The push connection to the phone is not a reliable connection. If you are having issues with the test connection failing, I would recommend switching to wifi if on 3g, and to 3g if on wifi. Usually one or the other will alleviate the problem.

**Comment by red261** [comment]
Thanks for the quick response. It's working now.
