### ISSUE TITLE
Web interface 'Test Connection' timing

### ISSUE THREAD

**Issue by jeremyparks** [ClockworkMod/DeskSMS#57]
When selecting 'Test Connection' from the web interface there doesn't seem to be enough time (or a race condition) before you declare a failure because, sometimes the 'Testing connection to phone...' will fade out and the 'connection failed' will pop up as the verification messages are coming in.

BTW - The connection failed banner is green, seems like red would be a more appropriate color for a failure. :P

**Comment by koush** [comment]
Yeah, I was considering raising it to 20 seconds last night. I'll probably end up doing that.
