### ISSUE TITLE
Clicking within the web app sms message box causes the message to send

### ISSUE THREAD

**Issue by phawxby** [ClockworkMod/DeskSMS#65]
Clicking within the sms message text box within the web app causes the message to send, which if you're clicking to correct an error can be quite frustrating.

**Comment by koush** [comment]
Is this a new bug? Or has this been around for a while?

**Comment by koush** [comment]
Bug should be fixed. Will take around 20 minutes for it to update on the servers.

**Comment by phawxby** [comment]
No idea, I only started using the apps today after updating rom manager and
finding out about it. I didn't see it in the active bugs so reported it.

**Comment by koush** [comment]
Cool thanks, was fixed.

**Comment by phawxby** [comment]
Fantastic. Thanks for the great support and great apps.
