### ISSUE TITLE
web interface

### ISSUE THREAD

**Issue by koush** [ClockworkMod/DeskSMS#7]
A web interface a la MightyText might be nice.

**Comment by srn** [comment]
If you're okay with MVC 3 I'm up for the task.

**Comment by koush** [comment]
@soerenn I am actually planning on making it entirely JavaScript based. There's no need for a server side component to this, other than the API. I'll release the API very shortly.

**Comment by koush** [comment]
Ie, static HTML + ajax calls against the server should be enough.

**Comment by srn** [comment]
Sounds cool. Update this thread when you have more information available about the API.

**Comment by koush** [comment]
API
https://github.com/ClockworkMod/DesktopSMSResources/wiki/DeskSMS-API
