### ISSUE TITLE
DeskSMS stops receiving/sending texts

### ISSUE THREAD

**Issue by pizzabackup** [ClockworkMod/DeskSMS#74]
I'll paste here what I wrote you ages ago on fb:

Me:
My free trial has just finished and I'd like to purchase the service, but before spending money I have had one issue: often connection just stop working, have to check the phone to see if the sms has been sent every time. Restarting wifi solves the problem but it comes back after 3 to 10 sms. Any help would be really appreciated :) 
Also, if this issue is going to be solved sooner or later I am paying right now, to support development.
Note: wifi sleep policy was set to "screen off", switched to "never" but it's still the same. I'm using my Nexus S on 2g.

DeskSMS:
Does everything work fine if you are plugged in and the phone is awake? (you can force it to stay awake while usb debugging). I believe this is a known issue that I will be fixing soon.

Me:
Even with screen turned on the bug occurs often. 

---

Nothing has changed since this summer, any news on this issue?  It's really annoying because the service isn't much reliable, always have to check the phone to see if I have replies or sending issues!

**Comment by Charana** [comment]
I don't know if this helps or if you have checked this already but I think mine stops working when my battery level goes to a certain level as my phone goes into power saver mode.
