### ISSUE TITLE
DeskSMS doesn't clear read SMS notifications from Android status bar

### ISSUE THREAD

**Issue by cell17** [ClockworkMod/DeskSMS#75]
After long sessions sending and replying to SMSes on the Chrome or general browser interface I return to my phone to find notifications for many unread SMSes on my status bar. Would it be possible for DeskSMS to clear these notifications once they've been read on the web interface, in the same way that reading an email on Gmail in my browser will clear the Gmail notification on my phone?

(fyi, my phone is running Android 4.0)

**Comment by scottopell** [comment]
I have this issue as well, android 4.0, galaxy nexus.

**Comment by koush** [comment]
It is not possible for one app to clear another app's notifications.

**Comment by danepowell** [comment]
Too bad... obviously not DeskSMS's fault, but still annoying. Could this be possible on rooted phones?
