### ISSUE TITLE
Double SMS sent when using webapp

### ISSUE THREAD

**Issue by fredespi** [ClockworkMod/DeskSMS#77]
Since I upgraded my sgs2 to ics, the desksms webapp sends double messages. This was also the case for the handcent app, until they fixed a timing problem. Perhaps desksms suffers from the same problem?

**Comment by aeons** [comment]
I can confirm the same problem (same phone, also upgraded to ICS).

**Comment by koush** [comment]
Uhh, what do you mean sends double messages? How are the messages being sent?

**Comment by koush** [comment]
Is this a CM ICS release?

**Comment by aeons** [comment]
It sends the same message twice. Same text, same recipient. Screenshot of a message sent to myself:

![Screenshot](http://i.imgur.com/sOwR5.png)

I'm running a rooted official firmware, ICS 4.0.2 on a European SGS2.

**Comment by fredespi** [comment]
I am running samsung ics 4.0.3 unrooted. Every third party sms app except the stock messaging app apparently has this problem.

**Comment by koush** [comment]
@fredespi Yikes. I don't have one of those on hand. But at least its comforting to know its happening with all third party apps. I would _maybe_ be able to fix it if I had one on hand (via some hacky workarounds), but you're going to need Samsung to fix it... since it is there bug.

**Comment by fredespi** [comment]
I upgraded the rom to Lp8 and it solved the problem.

/Fredrik
On May 10, 2012 6:48 PM, "Koushik Dutta" <
reply@reply.github.com>
wrote:

**Comment by koush** [comment]
Great

**Comment by brandon-dacrib** [comment]
I have this same problem. I am using a galaxy nexus 5. unrooted.

**Comment by mostlydev** [comment]
Same here, also Nexus 5.  I should point out that it only appears to send twice, but it actually only sends twice.  The second send entry shows a failed attempt.  I suppose if it succeeded then it would be double.  It's merely annoying, not prohibitive.
![image](https://f.cloud.github.com/assets/67087/1895252/e30c5b92-7b21-11e3-9adc-ee74aa8d739c.png)

**Comment by ssphillips** [comment]
I have the same issue with my Nexus 5. The first send fails every time, 2nd one goes through.
![5be0e0ec56729584b371ffe18f8b20d6](https://f.cloud.github.com/assets/5215769/1948482/ef8c4748-8093-11e3-9335-e3641ceabb53.png)
