### ISSUE TITLE
Chrome extension receiving/viewing text issue

### ISSUE THREAD

**Issue by pokerloser** [ClockworkMod/DeskSMS#78]
I am not able to see the incoming texts in the chrome extension.  I can see my side of the conversation and can send just fine through the extension.  Its just when i open it all I see is a big list of "me" sent texts and not the other side.

**Comment by koush** [comment]
Try using the sms time stamp adjuster. I assume you're on a motorola phone?

**Comment by pokerloser** [comment]
I changed the setting for -8 for Pacific Time and I am using a Droid
Bionic.  It didnt fix the issue. I get a pop up in chrome with the message
but when i use the extension its not there.  It looks like the extension
will only sync when i send a message either directly from the phone or the
extension, but never shows me the other persons texts.

On Thu, May 10, 2012 at 8:35 AM, Koushik Dutta <
reply@reply.github.com

> wrote:
> 
> Try using the sms time stamp adjuster. I assume you're on a motorola phone?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ClockworkMod/DeskSMS/issues/78#issuecomment-5628492

## 

Jeremy

**Comment by koush** [comment]
What's your login email?

**Comment by pokerloser** [comment]
jeremy.stern@gmail.com

On Thu, May 10, 2012 at 9:49 AM, Koushik Dutta <
reply@reply.github.com

> wrote:
> 
> What's your login email?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ClockworkMod/DeskSMS/issues/78#issuecomment-5630322

## 

Jeremy

**Comment by koush** [comment]
Try setting the adjustment to +12 or something. Your messages are coming in way in the past, so they aren't showing up.

That should make them show up. Then just adjust it downwards so that they are showing up at the right time relative to your messages. (You'll need to clear synced data from the DeskSMS menu when doing this)

This is a really irritating motorola bug,.

**Comment by pokerloser** [comment]
Its all confused now.  Now i can see the other persons side but not mine.
 I did do the clear sync data but didnt make a difference.  What should my
settings be in desksms and handcent. i think they are ouf sync with each
other

On Thu, May 10, 2012 at 9:56 AM, Koushik Dutta <
reply@reply.github.com

> wrote:
> 
> Try setting to to +12 or something. Your messages are coming in way in the
> past, so they aren't showing up.
> 
> That should make them show up. Then just adjust it downwards so that they
> are showing up at the right time relative to your messages. (You'll need to
> clear synced data from the DeskSMS menu when doing this)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ClockworkMod/DeskSMS/issues/78#issuecomment-5630495

## 

Jeremy

**Comment by koush** [comment]
Adjust it down to +8 now. Try tuning it until it all shows up.

**Comment by pokerloser** [comment]
I cant get them to line up, ive tried a bunch of different combinations and
it never aligns, pretty frustrating.

On Thu, May 10, 2012 at 10:57 AM, Koushik Dutta <
reply@reply.github.com

> wrote:
> 
> Adjust it down to +8 now. Try tuning it until it all shows up.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ClockworkMod/DeskSMS/issues/78#issuecomment-5632017

## 

Jeremy

**Comment by koush** [comment]
Ok, please set it to 0, and I'll see if I can fix it.

**Comment by koush** [comment]
Let me know once you've reset it to 0.

**Comment by koush** [comment]
Also, what is your phone number? I'll send you a few test messages.

**Comment by pokerloser** [comment]
ok, I disabled. Thanks so much for your help

On Thu, May 10, 2012 at 12:09 PM, Koushik Dutta <
reply@reply.github.com

> wrote:
> 
> Also, what is your phone number? I'll send you a few test messages.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ClockworkMod/DeskSMS/issues/78#issuecomment-5633892

## 

Jeremy

**Comment by pokerloser** [comment]
Were you able to make any progress on this?  Im seeing all the messages
that im sending, but not the other side.  Phone number is 949-525-1406.
Thanks

On Thu, May 10, 2012 at 12:09 PM, Koushik Dutta <
reply@reply.github.com

> wrote:
> 
> Also, what is your phone number? I'll send you a few test messages.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ClockworkMod/DeskSMS/issues/78#issuecomment-5633892

## 

Jeremy

**Comment by koush** [comment]
It seems to be 7 hours off. Try setting the adjust to +7, then clear synced data and force sync.

**Comment by pokerloser** [comment]
I got the first message ok, but the second never showed

On Fri, May 11, 2012 at 6:30 AM, Jeremy Stern jeremy.stern@gmail.comwrote:

> Were you able to make any progress on this?  Im seeing all the messages
> that im sending, but not the other side.  Phone number is 949-525-1406.
> Thanks
> 
> On Thu, May 10, 2012 at 12:09 PM, Koushik Dutta <
> reply@reply.github.com
> 
> > wrote:
> > 
> > Also, what is your phone number? I'll send you a few test messages.
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/ClockworkMod/DeskSMS/issues/78#issuecomment-5633892
> 
> ## 
> 
> Jeremy

## 

Jeremy

**Comment by pokerloser** [comment]
Changed to +7 but your test 3 message didnt come through after a clear and
sync

On Fri, May 11, 2012 at 9:40 AM, Koushik Dutta <
reply@reply.github.com

> wrote:
> 
> It seems to be 7 hours off. Try setting the adjust to +7, then clear
> synced data and force sync.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ClockworkMod/DeskSMS/issues/78#issuecomment-5655209

## 

Jeremy

**Comment by koush** [comment]
K sec

**Comment by koush** [comment]
You don't see this?

http://download.clockworkmod.com/screenshots//DeskSMS-20120511-095337.png

**Comment by pokerloser** [comment]
Nope, these are the first 2 entries in my chrome extension even after doing
a clear and sync:

[image: Inline image 1]

On Fri, May 11, 2012 at 9:53 AM, Koushik Dutta <
reply@reply.github.com

> wrote:
> 
> You don't see this?
> 
> http://download.clockworkmod.com/screenshots//DeskSMS-20120511-095337.png
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ClockworkMod/DeskSMS/issues/78#issuecomment-5655550

## 

Jeremy

**Comment by koush** [comment]
Go to chrome settings, show advanced, privacy settings, content settings.
All Sites and Cookie data
Search for DeskSMS and delete everything associated with it.

http://download.clockworkmod.com/screenshots//Settings_-_Cookies_and_site_data-20120511-095625.png

**Comment by koush** [comment]
Was unable to see your screenshot.

**Comment by koush** [comment]
Also, the chrome extension may need to be kicked. May want to restart Chrome. I'm thinking something is stuck after fixing the Motorola time bug, so I'm trying to reset DeskSMS on your browser to a default state.

**Comment by pokerloser** [comment]
Here it is attached.  I did the cookie removal but didnt change anything.

On Fri, May 11, 2012 at 9:58 AM, Koushik Dutta <
reply@reply.github.com

> wrote:
> 
> Also, the chrome extension may need to be kicked. May want to restart
> Chrome. I'm thinking something is stuck after fixing the Motorola time bug,
> so I'm trying to reset DeskSMS on your browser to a default state.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ClockworkMod/DeskSMS/issues/78#issuecomment-5655652

## 

Jeremy

**Comment by koush** [comment]
You have to do cookie and database and local storage removal.

I actually can't see your images unless you attach them as a URL. I am using the Github web interface, which doesnt handle images I guess.

**Comment by koush** [comment]
If you can ,try popping open the website
https://desksms.appspot.com and let me know if that is fixed.

Also try in another browser like Firefox if you have it. That will help me pinpoint the problem.

**Comment by pokerloser** [comment]
Ok, it looks like now mine arent showing up in the extension too.

On Fri, May 11, 2012 at 10:02 AM, Koushik Dutta <
reply@reply.github.com

> wrote:
> 
> You have to do cookie and database and local storage removal.
> 
> I actually can't see your images unless you attach them as a URL. I am
> using the Github web interface, which doesnt handle images I guess.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ClockworkMod/DeskSMS/issues/78#issuecomment-5655763

## 

Jeremy

**Comment by pokerloser** [comment]
Can you send me another test text?

On Fri, May 11, 2012 at 10:03 AM, Koushik Dutta <
reply@reply.github.com

> wrote:
> 
> If you can ,try popping open the website
> https://desksms.appspot.com and let me know if that is fixed.
> 
> Also try in another browser like Firefox if you have it. That will help me
> pinpoint the problem.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ClockworkMod/DeskSMS/issues/78#issuecomment-5655789

## 

Jeremy

**Comment by koush** [comment]
I'm going to delete a bunch of your texts first off the website. It won't be gone from your phone (and you can get it back if you just log into the phone again).

**Comment by pokerloser** [comment]
Ok.

On Fri, May 11, 2012 at 10:09 AM, Koushik Dutta <
reply@reply.github.com

> wrote:
> 
> I'm going to delete a bunch of your texts first off the website. It won't
> be gone from your phone (and you can get it back if you just log into the
> phone again).
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ClockworkMod/DeskSMS/issues/78#issuecomment-5655919

## 

Jeremy

**Comment by pokerloser** [comment]
The self test came through ok. just having a friend send me one to see if
everything lines up

On Fri, May 11, 2012 at 10:10 AM, Jeremy Stern jeremy.stern@gmail.comwrote:

> Ok.
> 
> On Fri, May 11, 2012 at 10:09 AM, Koushik Dutta <
> reply@reply.github.com
> 
> > wrote:
> > 
> > I'm going to delete a bunch of your texts first off the website. It won't
> > be gone from your phone (and you can get it back if you just log into the
> > phone again).
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/ClockworkMod/DeskSMS/issues/78#issuecomment-5655919
> 
> ## 
> 
> Jeremy

## 

Jeremy

**Comment by pokerloser** [comment]
His test came through ok, i think it might be good now. all the times line
up

On Fri, May 11, 2012 at 10:12 AM, Jeremy Stern jeremy.stern@gmail.comwrote:

> The self test came through ok. just having a friend send me one to see if
> everything lines up
> 
> On Fri, May 11, 2012 at 10:10 AM, Jeremy Stern jeremy.stern@gmail.comwrote:
> 
> > Ok.
> > 
> > On Fri, May 11, 2012 at 10:09 AM, Koushik Dutta <
> > reply@reply.github.com
> > 
> > > wrote:
> > > 
> > > I'm going to delete a bunch of your texts first off the website. It
> > > won't be gone from your phone (and you can get it back if you just log into
> > > the phone again).
> > > 
> > > ---
> > > 
> > > Reply to this email directly or view it on GitHub:
> > > https://github.com/ClockworkMod/DeskSMS/issues/78#issuecomment-5655919
> > 
> > ## 
> > 
> > Jeremy
> 
> ## 
> 
> Jeremy

## 

Jeremy

**Comment by koush** [comment]
Ok, I think I see what is going on now. Can you log into the Android app again?

**Comment by pokerloser** [comment]
How do i logout out of it? I open it and it shows me as logged in. do i
uninstall?

On Fri, May 11, 2012 at 10:13 AM, Koushik Dutta <
reply@reply.github.com

> wrote:
> 
> Ok, I think I see what is going on now. Can you log into the Android app
> again?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ClockworkMod/DeskSMS/issues/78#issuecomment-5655999

## 

Jeremy

**Comment by koush** [comment]
Yeah, everything seems fine. I cleared out some texts that were somehow marked as from the future (which were pushing all the new texts to the bottom or out completely).

If you log in again, it may resync all those messed up texts.

**Comment by pokerloser** [comment]
Ok, I will keep using it and let you know if anything gets out of whack
again.  Thanks so much for all your help.

On Fri, May 11, 2012 at 10:15 AM, Koushik Dutta <
reply@reply.github.com

> wrote:
> 
> Yeah, everything seems fine. I cleared out some texts that were somehow
> marked as from the future (which were pushing all the new texts to the
> bottom or out completely).
> 
> If you log in again, it may resync all those messed up texts.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ClockworkMod/DeskSMS/issues/78#issuecomment-5656051

## 

Jeremy

**Comment by pokerloser** [comment]
Something just happened.  I dont get the chrome pop up anymore down in the
corner and i dont get an uread message count in red in the extension icon.

On Fri, May 11, 2012 at 10:16 AM, Jeremy Stern jeremy.stern@gmail.comwrote:

> Ok, I will keep using it and let you know if anything gets out of whack
> again.  Thanks so much for all your help.
> 
> On Fri, May 11, 2012 at 10:15 AM, Koushik Dutta <
> reply@reply.github.com
> 
> > wrote:
> > 
> > Yeah, everything seems fine. I cleared out some texts that were somehow
> > marked as from the future (which were pushing all the new texts to the
> > bottom or out completely).
> > 
> > If you log in again, it may resync all those messed up texts.
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/ClockworkMod/DeskSMS/issues/78#issuecomment-5656051
> 
> ## 
> 
> Jeremy

## 

Jeremy

**Comment by koush** [comment]
Try enabling chrome notifications (I think they got turned off after the reset). Also, did you restart your browser?

**Comment by pokerloser** [comment]
Im seeing this weird timestamp issue again after the app was updated in the
google play store. Can you look into this?  Thanks,

On Fri, May 11, 2012 at 12:09 PM, Koushik Dutta <
reply@reply.github.com

> wrote:
> 
> I'm going to delete a bunch of your texts first off the website. It won't
> be gone from your phone (and you can get it back if you just log into the
> phone again).
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ClockworkMod/DeskSMS/issues/78#issuecomment-5655919

## 

Jeremy

**Comment by koush** [comment]
@pokerloser Do the time adjuster again?

**Comment by pokerloser** [comment]
It's set to plus 7. Never changed it since we last fixed it
On Jul 20, 2012 12:36 AM, "Koushik Dutta" <
reply@reply.github.com>
wrote:

**Comment by pokerloser** [comment]
My outbound texts are showing the correct timestamp, but its the ones i
receive are ahead 7 hours

On Fri, Jul 20, 2012 at 6:31 AM, Jeremy Stern jeremy.stern@gmail.comwrote:

> It's set to plus 7. Never changed it since we last fixed it
> On Jul 20, 2012 12:36 AM, "Koushik Dutta" <
> reply@reply.github.com>
> wrote:
> 
> > @pokerloser Do the time adjuster again?
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/ClockworkMod/DeskSMS/issues/78#issuecomment-7122732

## 

Jeremy

**Comment by koush** [comment]
@pokerloser Yes, set your timestamp adjust to 0 then. Play around with it to get it to line up.

Did you get a system update recently? Motorola may have fixed the bug?

**Comment by pokerloser** [comment]
Seems to have made it worse
On Jul 20, 2012 6:25 PM, "Koushik Dutta" <
reply@reply.github.com>
wrote:

**Comment by koush** [comment]
@pokerloser Can you try uninstall/reinstall of the app?

**Comment by pokerloser** [comment]
I did that, still terrible. If I change the time difference nothing shows
up. It's all over the place. Last time you look on the server and there
were a couple of messages stuck in there causing problems
On Jul 20, 2012 6:51 PM, "Koushik Dutta" <
reply@reply.github.com>
wrote:

**Comment by koush** [comment]
@pokerloser Ok, I'll take a look now. Can you try setting it to +12 in the meantime?

**Comment by pokerloser** [comment]
Done
On Jul 20, 2012 7:54 PM, "Koushik Dutta" <
reply@reply.github.com>
wrote:

**Comment by koush** [comment]
Actually, set it to +0 (disabled) now. I'll send you a few test messages to get this worked out. Let me know once it is disabled!

**Comment by pokerloser** [comment]
Done
On Jul 20, 2012 7:57 PM, "Koushik Dutta" <
reply@reply.github.com>
wrote:

**Comment by koush** [comment]
Ok, the messages I am seeing in are coming from the correct time on my end.

**Comment by koush** [comment]
Oh wait. Sec.

**Comment by koush** [comment]
Well, I've deleted all the messages from the server. It seems to be behaving properly again.

**Comment by pokerloser** [comment]
Thanks so much for the help.
On Jul 20, 2012 8:07 PM, "Koushik Dutta" <
reply@reply.github.com>
wrote:

**Comment by koush** [comment]
if this happens again in the future (i can't realy pinpoint what is causing it), just delete all your messages in the chat window.

**Comment by pokerloser** [comment]
Hello, im seeing this issue again.  I delete all the message like you said
but looks like the time if offset by -6 hours.  I tried to adjust the
settings on the app but it doesnt help.

On Fri, Jul 20, 2012 at 6:14 PM, Koushik Dutta <
reply@reply.github.com

> wrote:
> 
> if this happens again in the future (i can't realy pinpoint what is
> causing it), just delete all your messages in the chat window.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/ClockworkMod/DeskSMS/issues/78#issuecomment-7148851

## 

Jeremy

**Comment by pokerloser** [comment]
I set it to +7 and seems to be ok now, but had been disabled since last
time you fixed it.

On Tue, Aug 21, 2012 at 12:07 PM, Jeremy Stern jeremy.stern@gmail.comwrote:

> Hello, im seeing this issue again.  I delete all the message like you said
> but looks like the time if offset by -6 hours.  I tried to adjust the
> settings on the app but it doesnt help.
> 
> On Fri, Jul 20, 2012 at 6:14 PM, Koushik Dutta <
> reply@reply.github.com
> 
> > wrote:
> > 
> > if this happens again in the future (i can't realy pinpoint what is
> > causing it), just delete all your messages in the chat window.
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/ClockworkMod/DeskSMS/issues/78#issuecomment-7148851
> 
> ## 
> 
> Jeremy

## 

Jeremy
