### ISSUE TITLE
TabletSMS doesnt honor Jellybean rotation lock on N7

### ISSUE THREAD

**Issue by ChillingSilence** [ClockworkMod/DeskSMS#81]
Other apps such as G+ or Chrome will stay in portrait mode even when held in landscape orientation if you enable the software orientation / rotation lock from the notification bar.

If you hold the Nexus 7 in portrait, turn on the orientation lock, fire up TabletSMS then turn the tablet on its side and it will rotate (when it shouldn't).

**Comment by koush** [comment]
This is fixed, will release an update soon!

**Comment by koush** [comment]
Er, I actually did a few days ago now that I think about it. Just update!
