### ISSUE TITLE
TabletSMS Notifications/Refresh Stopped

### ISSUE THREAD

**Issue by pearlmikejam** [ClockworkMod/DeskSMS#85]
The latest update to TabletSMS stopped providing notifications.  TabletSMS does not update the messages in the list until the app is open, and even then, it takes some time for the update/refresh to occur.

I am experiencing this on a stock, unrooted, Wifi Motorola Xoom running Android 4.1.1.

For reference, DeskSMS is updating just fine on my Chrome browser of my laptop, so this seems to be isolated to the tablet app.

**Comment by pearlmikejam** [comment]
Update: After having cleared cache several times, I cleared data and set up the app again.  That seems to have corrected my issues.  It appears there may be some limit to the number of messages the app can manage.

**Comment by koush** [comment]
I recently fixed this so that it automatically purges SMS older than 3 weeks. Please let me know if this problem resurfaces.
