### ISSUE TITLE
DeskSMS won't send texts to phone but can receive them

### ISSUE THREAD

**Issue by Mathiew** [ClockworkMod/DeskSMS#86]
DeskSMS was working fine for months but now it stopped working properly for some strange reason. From any browser, DeskSMS syncs the messages on my phone but can't send any anymore. 

I am using an LG Optimus LTE P935.

Can anyone help or does anyone have a similar problem?

Thanks in advance,

Mathiew

**Comment by chaoticbear** [comment]
I'm also having this issue:

I'm receiving texts in Gtalk, but when I respond to them through Gtalk they never get sent out.

No errors are being given. 

DeskSMS shows no available updates.

LG Spectrum VS920 (Running ICS 4.0.4)

Thanks,
Josh

**Comment by chaoticbear** [comment]
Also tried from desksms site, and tried uninstall/reinstall app.

**Comment by Mathiew** [comment]
yeah this is messed up. it was working before... I've tried everything I can think of. I emailed desksms but they haven't responded either...

**Comment by koush** [comment]
Will take a look now.

**Comment by koush** [comment]
Hi guys.

I'm unable to reproduce this problem. What gtalk client are you using? I am using Adium on Mac.
If you let me know what chat client you are using, I would be happy to look into this issue further.

Thanks!

**Comment by Mathiew** [comment]
Hi, 

Thanks for looking into this. I am just using the standard gmail chat. It doesn't matter if I text by email or by using your site at https://desksms.appspot.com/, I can receive texts but not text from it.

**Comment by koush** [comment]
@Mathiew Oh, I thought this problem was isolated to Gtalk. It seems like it is just a general push failure then.

Can you try using the Chrome to Phone app by Google and see if that works? That also uses the push transport. If that doesn't work either, that indicates just a general push connection issue with your phone, rather than a DeskSMS problem.

**Comment by Mathiew** [comment]
I just updated this comment: the chrome to phone app DOES work. I was just logged into the wrong google account.... the DeskSMS still won't work..

**Comment by koush** [comment]
@Mathiew So DeskSMS works too?

**Comment by Mathiew** [comment]
@koush no desksms does not work. it can only receive texts. when i click test connection it says it works but phone won't receive the text.

**Comment by koush** [comment]
@Mathiew What's your login email? I'll need to investigate your account

**Comment by Mathiew** [comment]
@koush it's just my name backwards at gmail.com, weihtam@gmail.com

**Comment by chaoticbear** [comment]
mine is joshfphone@gmail.com

Josh Fleming
Revolt Media : Web Development, Print & Multimedia Production
revoltmedia.com / (619) 864-1184

**Comment by chaoticbear** [comment]
Any luck with this? Could there be a new ICS permission thing we need to enable?

**Comment by Mathiew** [comment]
@koush I just wanted to point out that although I can't text from Desksms I can call people though. Just an fyi as you look into the problem.

**Comment by Mathiew** [comment]
@joshfleming I just gave up on desksms. I suggest you try might text. It's free and I personally like it better than desksms.

**Comment by koush** [comment]
@Mathiew I pulled the desksms logs off your phone, and found this:

W/System.err(10412): java.lang.NullPointerException
W/System.err(10412):    at com.lge.mdm.uimanager.adapter.LGMDMUIMessageAdapter.isAllowSendMessage(LGMDMUIMessageAdapter.java:50)
W/System.err(10412):    at com.lge.mdm.MDMInterfaceImpl.isAllowSendMessage(MDMInterfaceImpl.java:110)
W/System.err(10412):    at android.telephony.SmsManager.sendMultipartTextMessage(SmsManager.java:328)
W/System.err(10412):    at com.koushikdutta.desktopsms.SyncService.a(Unknown Source)
W/System.err(10412):    at com.koushikdutta.desktopsms.SyncService.c(Unknown Source)
W/System.err(10412):    at com.koushikdutta.desktopsms.SyncService.d(Unknown Source)
W/System.err(10412):    at com.koushikdutta.desktopsms.SyncService.a(Unknown Source)
W/System.err(10412):    at com.koushikdutta.desktopsms.bw.run(Unknown Source)

Your MDM (mobile device management) policy is not allowing text messages to be sent.

**Comment by koush** [comment]
@joshfleming If you can try sending a message via desksms gtalk and pull a log for me, I can investigate further.

Since I do not have access to your gtalk account, I can't help from my end. However, sending a message via the web interface worked fine.

Let me know which gtalk client you use.

**Comment by Mathiew** [comment]
@koush how would I change the MDM policy? desksms was working fine for months until a week after I bought a new phone.

**Comment by koush** [comment]
@Mathiew 
Are you connected to an Exchange server? I'm not familiar with LG phones (which is what I think you have).

**Comment by chaoticbear** [comment]
I've since flashed back to android 2.3.6 and desksms works, So I'm unable
to help troubleshoot the problem in ICS... Sorry.

Josh Fleming
Revolt Media : Web Development, Print & Multimedia Production
revoltmedia.com / (619) 864-1184

**Comment by koush** [comment]
@Mathiew 
Here's a test version of the DeskSMS apk that sends the SMS using another method.

http://download.clockworkmod.com/test/DesktopSms.apk

Try that and let me know if it works.

**Comment by Mathiew** [comment]
@koush  I am not connected to an exchange server. Desksms doesn't work on my Samsung Galaxy S1 anymore either.

I downloaded your test version and when I text from the computer I can see the outgoing message as sent on my computer but it does not actually get sent.

**Comment by koush** [comment]
@Mathiew Can you check and see if a third party SMS app can send messages?

**Comment by Mathiew** [comment]
@koush I am using Mighty Text and it is working just fine. It uses basically the same Google Login method as Desksms so I don't know why Desksms doesn't work anymore

**Comment by koush** [comment]
@Mathiew Hi Mathiew, I appreciate your patience.

Can you install this and let me know if it fixes the issue.

http://download.clockworkmod.com/test/DesktopSms2.apk

**Comment by Mathiew** [comment]
@koush yes that works!!! Thanks.

**Comment by koush** [comment]
@Mathiew Sigh. Ok. I had to work around some manufacturer specific bugs. Basically, whatever firmware you are running is _requiring_ optional parameters when sending out SMS. Frustrating!

**Comment by JavierSolis** [comment]
hi @koush what is the optional parameter?
