### ISSUE TITLE
Screen switching on for no reason at 4.2

### ISSUE THREAD

**Issue by aericson** [ClockworkMod/DeskSMS#87]
Screen is getting turned on for no apparent reason on 4.2. Not sure if it is just with me. Please let me know if you can't reproduce the problem.

logcat excerpt:

I/C2DMReceiver( 1430): Tickle received!
W/GTalkService(  804): [DataMsgMgr] broadcast intent callback: result=CANCELLED forIntent { act=com.google.android.c2dm.intent.RECEIVE pkg=com.koushikdutta.desktopsms (has extras) }
I/SyncService( 1430): Service starting
I/SyncService( 1430): Version: 1110
I/SyncService( 1430): ============= Sync Reason outbox=============
I/SyncService( 1430): ================Checking outbox================
I/SyncService( 1430): ================Sending outbox================
I/PowerManagerService(  392): Waking up from sleep...
I/ActivityManager(  392): Process com.twitter.android (pid 7890) has died.
I/WindowManager(  392): Lock screen displayed!
D/PowerManagerService-JNI(  392): Excessive delay in autosuspend_disable() while turning screen on: 353ms
D/SurfaceFlinger(  129): Screen acquired, type=0 flinger=0x40130348
I/SyncService( 1430): ================No new messages================
I/SyncService( 1430): ================No new messages================
I/SyncService( 1430): ================No new messages================
I/SyncService( 1430): ================No new messages================
I/SyncService( 1430): ================No new messages================
I/SyncService( 1430): ================No new messages================
I/SyncService( 1430): ================No new messages================
I/SyncService( 1430): ================No new messages================
I/SyncService( 1430): ================No new messages================
I/SyncService( 1430): ================No new messages================
I/SyncService( 1430): ================No new messages================
I/SyncService( 1430): ================No new messages================
D/dalvikvm( 1430): GC_CONCURRENT freed 353K, 5% free 9275K/9684K, paused 3ms+3ms, total 27ms
I/SyncService( 1430): ================No new messages================
I/SyncService( 1430): ================No new messages================
I/SyncService( 1430): ================No new messages================

**Comment by koush** [comment]
Fixed in the latest builds.
