### ISSUE TITLE
Can't send SMS

### ISSUE THREAD

**Issue by davr** [ClockworkMod/DeskSMS#90]
This used to work fine, but a while ago I stopped being able to send SMS. The Test Connection from the browser app works fine, the "Send Test Message" works fine, but when I send a SMS from the browser app, it sticks at "Text message delivery pending..." and never shows up on my phone. My symptoms seem similar or the same as issue #86 My account is drorex@gmail.com

**Comment by koush** [comment]
Please test again. You may need to restart Chrome. I restarted a service on my end that may have gotten stuck.
