### ISSUE TITLE
Sent/recv'd SMS messages on phone not sending through DeskSMS

### ISSUE THREAD

**Issue by ianmarcinkowski** [ClockworkMod/DeskSMS#97]
Device: Galaxy Nexus GSM
Android Version: Stock 4.2.2 (Rooted)
Notification methods activated: Gmail, GTalk and Web interface

Since the service went over quota earlier this week, SMS messages received on my Galaxy Nexus will not send notifications to my configured notification methods (GTalk, Gmail, etc.)

Test notifications initiated from the web app are working.  The Test Connection button in the web interface will send a message via GTalk from desksms@desksms.appspot.com to my account.  This message will also show up in the web interface.

Test notifications from sent from the DeskSMS app on my phone will send an SMS message to my phone number.

This message will not show up in the web interface or my GTalk account.  This is the same for any SMS messages received on my phone.

In case it matters, I have recently renewed my subscription via an in-app purchase.  My subscription is shown to be valid in the Android App.

**Comment by invaderdag** [comment]
I have the same issue, I also recently purchased a subscription.

**Comment by ianmarcinkowski** [comment]
Would logcat output help diagnose this issue?

**Comment by ianmarcinkowski** [comment]
Hit the wrong button.  Oops.

**Comment by ianmarcinkowski** [comment]
This issue disappeared when I unstalled and reinstalled the DeskSMS app on my phone.
